channels:
    - lcdb
    - bioconda
    - r
    - defaults
    - conda-forge
dependencies:
    - bedtools
    - biopython
    - lcdblib
    - python ==3.5
    - pandoc
    - samtools
    - snakemake
    - r-argparse
    - r-rcpp
    - r-lattice
    - r-digest
    - r-foreign
    - r-gtable
    - r-lazyeval
    - r-mnormt
    - r-munsell
    - r-nlme
    - r-nnet
    - r-plyr
    - r-psych
    - r-reshape2
    - r-dplyr
    - r-rcolorbrewer
    - r-devtools
    - r-ggplot2
    - r-rmarkdown
    - r-knitrbootstrap
    - bioconductor-deseq2

  #  - r-misctools
  # - r-depmixs4
  #  - r-rsolnp
  #  - r-stringi
  #  - r-stringr
  #  - r-tibble
  #  - r-truncnorm
